config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    resistrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'informations#index'
  get '/about', to: 'informations#about'

  resources :users

  
  resources :inquiries, only: [:new, :create]

  resources :works, only: [:index, :show] 
    namespace :admin do
      resources :works, only: [:new, :create, :edit, :update, :destroy]
      resources :categories, only: [:index, :new, :create, :destroy]
    end
  end

app/views/shared/_footer.html.haml
%nav.footer__nav.col-12.navbar.justify-content-center
  %ul.page-nav.d-flex.justify-content-between.col-9
    = render 'shared/page-nav'
    -if current_user
      %li=link_to 'Logout', destroy_user_session_path, method: :delete, class: 'page-nav__list'
    - else
      %li=link_to 'Admin Login', new_user_session_path, class: 'page-nav__list'

.col.d-flex.justify-content-center
  .back-to-top#back-to-top
    = fa_icon("arrow-up")

%small.copy.col-12.text-center
  Copy Right &copy;
  %span= @year
  Seino Azumi, All Rights Reserved.

app/views/shared/_header.html.haml
%header.header.row.d-flex.justify-content-between
  %nav.header__nav--l.navbar.col-2
    .social-link.w-100.d-flex.justify-content-between
      =link_to "https://www.facebook.com/seinoazumi", class: 'social-link__icon text-center pt-1 mr-3', target: '_new' do
        %span=fa_icon("facebook-f")
      =link_to "https://twitter.com/azmengineer", class: 'social-link__icon text-center pt-1', target: '_new' do
        %span=fa_icon("twitter")

  %nav.header__nav--r.col-md-6.navbar.d-none.d-md-block
    %ul.page-nav.d-flex.justify-content-between.pt-3
      = render 'shared/page-nav'

  %nav.header__nav--sp.d-md-none
    .menu-btn.pt-4#menu-btn
      = fa_icon("bars")
    .sp-page-nav
      %ul.sp-page-nav__block.text-center#page-nav-block
        = render 'shared/page-nav'

app/views/shared/_page-nav.html.haml
%li=link_to 'Home', root_path , class: 'page-nav__list col'
%li=link_to 'About', about_path , class: 'page-nav__list col'
%li=link_to 'Works', works_path , class: 'page-nav__list col'
%li=link_to 'Blog', root_path(anchor: "blog"), class: 'page-nav__list col'